# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: motion_planner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'motion_planner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14motion_planner.proto\x12\rmotionplanner\"W\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02qx\x18\x04 \x01(\x01\x12\n\n\x02qy\x18\x05 \x01(\x01\x12\n\n\x02qz\x18\x06 \x01(\x01\x12\n\n\x02qw\x18\x07 \x01(\x01\"\x1d\n\x0bJointValues\x12\x0e\n\x06values\x18\x01 \x03(\x01\"j\n\x0cMoveLRequest\x12(\n\x0btarget_pose\x18\x01 \x01(\x0b\x32\x13.motionplanner.Pose\x12\x30\n\x0cstart_joints\x18\x02 \x01(\x0b\x32\x1a.motionplanner.JointValues\"s\n\x0cMoveJRequest\x12\x31\n\rtarget_joints\x18\x01 \x01(\x0b\x32\x1a.motionplanner.JointValues\x12\x30\n\x0cstart_joints\x18\x02 \x01(\x0b\x32\x1a.motionplanner.JointValues\"b\n\x0eMotionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\ntrajectory\x18\x03 \x03(\x0b\x32\x1a.motionplanner.JointValues\"\'\n\x10SetConfigRequest\x12\x13\n\x0b\x63onfig_yaml\x18\x01 \x01(\t\"5\n\x11SetConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe9\x01\n\rMotionPlanner\x12\x43\n\x05MoveL\x12\x1b.motionplanner.MoveLRequest\x1a\x1d.motionplanner.MotionResponse\x12\x43\n\x05MoveJ\x12\x1b.motionplanner.MoveJRequest\x1a\x1d.motionplanner.MotionResponse\x12N\n\tSetConfig\x12\x1f.motionplanner.SetConfigRequest\x1a .motionplanner.SetConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motion_planner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSE']._serialized_start=39
  _globals['_POSE']._serialized_end=126
  _globals['_JOINTVALUES']._serialized_start=128
  _globals['_JOINTVALUES']._serialized_end=157
  _globals['_MOVELREQUEST']._serialized_start=159
  _globals['_MOVELREQUEST']._serialized_end=265
  _globals['_MOVEJREQUEST']._serialized_start=267
  _globals['_MOVEJREQUEST']._serialized_end=382
  _globals['_MOTIONRESPONSE']._serialized_start=384
  _globals['_MOTIONRESPONSE']._serialized_end=482
  _globals['_SETCONFIGREQUEST']._serialized_start=484
  _globals['_SETCONFIGREQUEST']._serialized_end=523
  _globals['_SETCONFIGRESPONSE']._serialized_start=525
  _globals['_SETCONFIGRESPONSE']._serialized_end=578
  _globals['_MOTIONPLANNER']._serialized_start=581
  _globals['_MOTIONPLANNER']._serialized_end=814
# @@protoc_insertion_point(module_scope)
