# Default initial positions for gantry's ros2_control fake system

initial_positions:
  linear_rail: 0
  ur_elbow_joint: 0
  ur_shoulder_lift_joint: 0
  ur_shoulder_pan_joint: 0
  ur_wrist_1_joint: 0
  ur_wrist_2_joint: 0
  ur_wrist_3_joint: 0