ur5e_gantry:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  planning_pipelines:
    pipelines:
      ompl:
        planning_plugin: ompl_interface/OMPLPlanner
      pilz_industrial_motion_planner:
        planning_plugin: pilz_industrial_motion_planner/CommandPlanner
      